### ISSUE TITLE
Suggest the new `strip` option for contracts' `Cargo.toml`

### ISSUE THREAD

**Issue by tedbyron** [near/docs#1161]
Right now the docs [here](https://www.near-sdk.io/reducing-contract-size/examples#using-flags) recommend using rustc flags to pass the `-s` flag to the linker, which will then strip the resulting binary of all symbols.

Rust 1.59.0 added a new compiler flag [`-C strip`](https://doc.rust-lang.org/rustc/codegen-options/index.html#strip). [Cargo supports this](https://doc.rust-lang.org/cargo/reference/profiles.html#strip) in profiles. Instead of adding a `.cargo/config`/`.cargo/config.toml` file, contract writers can just add a line to their release profile in `Cargo.toml`:

```toml
[package]
# ...

[profile.release]
strip = "symbols" # strip all symbols
# or
strip = "debuginfo" # strip debug symbols
```

Right now there is an [issue](https://github.com/rust-lang/rust/issues/93294) when compiling to WASM with `strip = "symbols"`, but once this is resolved it should be recommended over passing compiler flags to Cargo.
